name: Build Deep Live Cam Executables

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write   # 👈 required for creating/uploading releases

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Verify Python version
        run: python --version

      - name: Free disk space (macOS only)
        if: runner.os == 'macOS'
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          df -h

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile run.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deep-live-cam-${{ matrix.os }}
          path: dist/*

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          generate_release_notes: true  # 👈 auto-generate release if missing
